name: deploy
on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: data-collector image metadata
        id: meta_data_collector
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}-data-collector
          labels: |
            org.opencontainers.image.licenses=GPL-3.0-or-later
      - name: data-collector image build
        uses: docker/build-push-action@v2
        with:
          context: ./data-collector/
          file: ./data-collector/Dockerfile
          push: true
          tags: ${{ steps.meta_data_collector.outputs.tags }}
          labels: ${{ steps.meta_data_collector.outputs.labels }}

      - name: evaluation_dashboard image metadata
        id: meta_evaluation_dashboard
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}-dashboard
          labels: |
            org.opencontainers.image.licenses=GPL-3.0-or-later
      - name: Services image build
        uses: docker/build-push-action@v2
        with:
          context: ./evaluation_dashboards/
          file: ./evaluation_dashboards/Dockerfile
          push: true
          tags: ${{ steps.meta_evaluation_dashboard.outputs.tags }}
          labels: ${{ steps.meta_evaluation_dashboard.outputs.labels }}

      - name: Migration image metadata
        id: meta_migration
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}-migration
          labels: |
            org.opencontainers.image.licenses=GPL-3.0-or-later
      - name: Migration image build
        uses: docker/build-push-action@v2
        with:
          context: ./pg-database/
          file: ./pg-database/Dockerfile.migration
          push: true
          tags: ${{ steps.meta_migration.outputs.tags }}
          labels: ${{ steps.meta_migration.outputs.labels }}